apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /srv/nfs/zookeeper
    server: ocp.thales.com
